In [1]:
import pandas as pd

In [9]:
df=pd.read_excel('FR007利率互换收盘曲线（全）(1).xls',index_col=0)[1:]
df.index.name='Time'
df

,FR007利率互换收盘曲线_均值:1M,FR007利率互换收盘曲线_均值:3M,FR007利率互换收盘曲线_均值:6M,FR007利率互换收盘曲线_均值:9M,FR007利率互换收盘曲线_均值:1Y,FR007利率互换收盘曲线_均值:2Y,FR007利率互换收盘曲线_均值:3Y,FR007利率互换收盘曲线_均值:4Y,FR007利率互换收盘曲线_均值:5Y,FR007利率互换收盘曲线_均值:7Y,...,中债进出口行债到期收益率:3年,中债进出口行债到期收益率:4年,中债进出口行债到期收益率:5年,中债进出口行债到期收益率:6年,中债进出口行债到期收益率:7年,中债进出口行债到期收益率:8年,中债进出口行债到期收益率:9年,中债进出口行债到期收益率:10年,中债进出口行债到期收益率:15年,中债进出口行债到期收益率:20年
Time,,,,,,,,,,,,,,,,,,,,,
2002-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8075,2.9474,3.08,3.2054,3.3236,3.4346,3.5383,3.6348,4.0087,4.202
2002-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8656,3.0057,3.1385,3.2638,3.3816,3.492,3.595,3.6906,4.0569,4.2375
2002-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7964,2.9607,3.1161,3.2627,3.4005,3.5294,3.6495,3.7607,4.1843,4.3868
2002-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8112,2.9741,3.128,3.2731,3.4093,3.5366,3.6549,3.7644,4.1785,4.3702
2002-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8157,2.9789,3.1331,3.2783,3.4147,3.5421,3.6606,3.7702,4.184,4.3747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-08 00:00:00,2.1554,2.3513,2.3888,2.4275,2.4589,2.56,2.6563,2.7499,2.8375,2.97,...,3.0875,3.2411,3.2695,3.4161,3.4604,3.6201,3.6399,3.6405,3.8797,3.9026
2021-01-11 00:00:00,2.0987,2.355,2.3988,2.4313,2.4663,2.5663,2.67,2.7638,2.8538,2.99,...,3.0968,3.2491,3.2856,3.4272,3.4707,3.6251,3.6396,3.6771,3.8847,3.9077
2021-01-12 00:00:00,2.0566,2.3077,2.3688,2.4095,2.44,2.5405,2.6413,2.7363,2.8265,2.9634,...,3.0886,3.2393,3.2765,3.4235,3.4624,3.6208,3.6394,3.6527,3.855,3.9033
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
数据来源: 中债估值中心,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
new_col_name=[]
for col in df.columns:
#     print(col)
    col=col.replace('利率互换收盘曲线_均值','')
    col=col.replace('中债国债到期收益率','国债')
    col=col.replace('中债国开债到期收益率','国开')
    col=col.replace('中债进出口行债到期收益率','口行')
    
    col=col.replace('个月','M')
    col=col.replace('年','Y')
    new_col_name.append(col)
df.columns=new_col_name
df.index=list(map(lambda x:str(x)[:10],df.index.tolist()))
df.index.name='Time'
df

,FR007:1M,FR007:3M,FR007:6M,FR007:9M,FR007:1Y,FR007:2Y,FR007:3Y,FR007:4Y,FR007:5Y,FR007:7Y,...,口行:3Y,口行:4Y,口行:5Y,口行:6Y,口行:7Y,口行:8Y,口行:9Y,口行:10Y,口行:15Y,口行:20Y
Time,,,,,,,,,,,,,,,,,,,,,
2002-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8075,2.9474,3.08,3.2054,3.3236,3.4346,3.5383,3.6348,4.0087,4.202
2002-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8656,3.0057,3.1385,3.2638,3.3816,3.492,3.595,3.6906,4.0569,4.2375
2002-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7964,2.9607,3.1161,3.2627,3.4005,3.5294,3.6495,3.7607,4.1843,4.3868
2002-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8112,2.9741,3.128,3.2731,3.4093,3.5366,3.6549,3.7644,4.1785,4.3702
2002-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8157,2.9789,3.1331,3.2783,3.4147,3.5421,3.6606,3.7702,4.184,4.3747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-08,2.1554,2.3513,2.3888,2.4275,2.4589,2.56,2.6563,2.7499,2.8375,2.97,...,3.0875,3.2411,3.2695,3.4161,3.4604,3.6201,3.6399,3.6405,3.8797,3.9026
2021-01-11,2.0987,2.355,2.3988,2.4313,2.4663,2.5663,2.67,2.7638,2.8538,2.99,...,3.0968,3.2491,3.2856,3.4272,3.4707,3.6251,3.6396,3.6771,3.8847,3.9077
2021-01-12,2.0566,2.3077,2.3688,2.4095,2.44,2.5405,2.6413,2.7363,2.8265,2.9634,...,3.0886,3.2393,3.2765,3.4235,3.4624,3.6208,3.6394,3.6527,3.855,3.9033
nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
数据来源: 中债估值,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import re 
main_time=[x for x in df.columns if re.search('1Y|2Y|3Y|:5Y|7Y|10Y',x)]
new=df.loc[:,main_time].dropna()
# new.to_csv('各基准利率数据.csv')
new.to_csv('../data/IRS/各基准利率数据.csv')